### ISSUE TITLE
Allow Sending Rand Values to Rune

### ISSUE THREAD

**Issue by f0rodo** [hotg-ai/rune#138]
Current I cannot run the sine rune example with my own inputs. Also I can't see the input given

```➜  rune git:(master) ✗ cat test.raw
0.2
1.0
-2
1.2
4.2
0.0
➜  rune git:(master) ✗ RUST_LOG=info cargo run --bin rune --release -- run examples/sine/sine.rune --capability=rand:test.raw -r 10
    Finished release [optimized] target(s) in 0.19s
     Running `target/release/rune run examples/sine/sine.rune '--capability=rand:test.raw' -r 10`
[2021-05-09T18:57:01.423Z INFO  rune::run] Running rune: examples/sine/sine.rune
[2021-05-09T18:57:01.439Z INFO  runicos_base::image] Serial: {"type_name":"f32","channel":2,"elements":[4.8617184e-2],"dimensions":[1]}```

**Comment by Ge-te** [comment]
This sine rune works for me:
`FROM runicos/base

CAPABILITY<F32> input RAW
PROC_BLOCK<F32,F32> mod360 hotg-ai/rune#proc_blocks/modulo --modulus 360.0

MODEL<F32, F32> sine ./sinemodel.tflite

OUT serial

RUN input mod360 sine serial
`

**Comment by f0rodo** [comment]
awesome! Thanks

**Comment by Michael-F-Bryan** [comment]
I believe this can be closed because you can accomplish it via the `RAW` capability. @kthakore, feel free to reopen it if you think there's more we can do from the `rune` side.
