### ISSUE TITLE
For image capability, need to extract from manifest what imagesize is, if its RGB BGR YUV or Grayscale

### ISSUE THREAD

**Issue by Ge-te** [hotg-ai/rune#146]
Need these parameters to reformat in app.
Needs to be send from
manifest -> SDK -> App

Links to https://github.com/hotg-ai/rune_vm/issues/3

**Comment by Michael-F-Bryan** [comment]
According to image-rs/image#1217 the [`image`](https://docs.rs/image) crate doesn't support YUV images, but we can convert between everything else.
