### ISSUE TITLE
Change host functions to allow models to have multiple inputs/outputs

### ISSUE THREAD

**Issue by Michael-F-Bryan** [hotg-ai/rune#164]
With #163, everything implemented in Rust can have multiple inputs and outputs (proc blocks, the SERIAL output, etc.), however anything which needs to pass tensors back and forth across the Rune-Runtime boundary [can only have one input and one output](https://github.com/hotg-ai/rune/blob/7312198e61767e8c9392b90c5962296077f67b1c/runic-types/src/wasm32/intrinsics.rs#L7-L18).

To support models like yamnet, we'll need to change our host functions to allow multiple inputs and multiple outputs.

CC @delimbetov because this will affect the C++ runtime.

**Comment by delimbetov** [comment]
On cpp side it's less than an hour of work. Tflite wrapper already supports multiple inputs/outputs. Only host function will have to be reimplemented
