### ISSUE TITLE
Rune standalone mode v.s. linked mode

### ISSUE THREAD

**Issue by f0rodo** [hotg-ai/rune#193]
Sometimes model labels and embeddings files can be massive. We need an ability to link to these resources so that each time a Rune is updated the whole label file doesn't needs to be sent over the wire. One approach is to have standalone mode (which is what we have now) or linked mode. 

In Linked Mode certain static arguments for proc blocks (labels/embedding lookups] can be sent by provider at runtime. The provider can chose to load this from a file or URL or etc.

**Comment by Michael-F-Bryan** [comment]
I'd say this is solved quite elegantly using embedded resources (#228). If you want a model or file to be linked in at runtime, declare a resource and have the runtime provide it.
