### ISSUE TITLE
Unable to publish to crates.io due to naming conflict

### ISSUE THREAD

**Issue by Michael-F-Bryan** [hotg-ai/rune#222]
We can't publish the `rune-XXX` crates to crates.io because [a Rune project already exists](https://crates.io/search?q=rune) and it already has a bunch of `rune-XXX` crates.

I'm guessing the best solution would be to publish as `hotg-rune-XXX`, but for crates like `hotg-rune-proc-block-macros` the names are starting to get ridiculously long.

@akshr and @kthakore, can you think of a better solution? 

This is blocking #210.

**Comment by kthakore** [comment]
Could we do a private crates? Is hmr-* taken?
