### ISSUE TITLE
Allow sepecifying multiple capabilities of the same type

### ISSUE THREAD

**Issue by Michael-F-Bryan** [hotg-ai/rune#224]
In #223 we made sure each image capability in the style transfer Rune had a `source: N` argument. @Ge-te is working on allowing multiple instances of the same capability in our Flutter code, but we still need to make sure the `rune run` command supports it.

**Comment by kthakore** [comment]
wouldn't we want some Id at some-point instead of an int? I am thinking we should think of a type of capabilities.

This helps us solve that problem
of multiple cameras etc. I think we may need N to be a byte array for a sha hash.

**Comment by Michael-F-Bryan** [comment]
I was thinking we could change capability and proc block arguments so they are just strings.

Like you say, that approach would make things a lot more flexible and we can also piggy-back off the normal `FromStr` machinery (i.e. `string.parse()`).

That change would also remove a lot of complexity... At the moment an argument can be one of `i32`, `i64`, `f32`, or `f64`, and you need to handle that. It also simplifies passing the capability parameter from Rune to the runtime because you are just passing a string instead of encoding it as bytes and passing the pointer and value type. This also lets us remove a bunch of now-unnecessary types from the `rune-core` crate.

**Comment by Michael-F-Bryan** [comment]
Fixed in #233.
