### ISSUE TITLE
Unable to build Runes with Local Proc Blocks

### ISSUE THREAD

**Issue by Mi1ind** [hotg-ai/rune#225]
Calling a proc_block locally in The `Runfile.yml`
```yaml
  audio_float_conversion:
    proc-block: "../rune/proc_block/audio_float_conversion"
```
Provides the following error when running `rune build Runefile.yml`.
```rust
error[E0599]: no method named `set_output_dimensions` found for struct `AudioFloatConversion` in the current scope
  --> lib.rs:23:15
   |
23 |     normalize.set_output_dimensions(&[6144usize]);
   |               ^^^^^^^^^^^^^^^^^^^^^ method not found in `AudioFloatConversion`
   | 
  ::: /Users/milind/GitHub/hotg-ai/rune/runic-types/src/pipelines.rs:23:8
   |
23 |     fn set_output_dimensions(&mut self, _dimensions: &[usize]) {}
   |        --------------------- the method is available for `AudioFloatConversion` here
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
6  | use runic_types::pipelines::HasOutputs;
```

However, there is nothing wrong with the proc_block itself - it builds when called from the master branch in the rune repo, but fails when built locally (Tested this with the image-normalization proc block).

**Comment by Michael-F-Bryan** [comment]
Can you do a `cargo update` and try again? The fact that you are pulling in `runic_types` indicates you are probably using an old git dependency, because that crate was renamed to `rune-core` in #207.

**Comment by Michael-F-Bryan** [comment]
@Mi1ind, I'm going to close this issue for now. Feel free to reopen it if the issue persists.
