### ISSUE TITLE
Build fails when installing the cli

### ISSUE THREAD

**Issue by amar-1977** [hotg-ai/rune#284]
I'm following the [tutorial](https://hotg.dev/docs/).

When I run the  [install command](https://hotg.dev/docs/#install-from-source), the complier fails and I see the following error:

`the trait bound `toml::Value: Default` is not satisfied`
.../.cargo/registry/src/github.com-1ecc6299db9ec823/hotg-rune-codegen-0.6.0/src/manifest.rs:29:25

The error seems to be pointing to [these lines](https://github.com/hotg-ai/rune/blob/8a2fc8726ad4594326743c7447251cad501b9e45/crates/codegen/src/manifest.rs#L29-#L32) in the manifest file.

Here's the error message in its entirety:

workspace: Some(Workspace {
|  _________________________^
| |             members: vec![String::from(".")],
| |             default_members: vec![String::from(".")],
| |             ..Default::default()
| |         }),
| |_________^ the trait `Default` is not implemented for `toml::Value`
|
   = note: required because of the requirements on the impl of `Default` for `Workspace`
   = note: required by `std::default::Default::default`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `hotg-rune-codegen`

**Comment by Michael-F-Bryan** [comment]
I think this was caused by a backwards-incompatible change in `cargo_toml` and CI never picked it up because we commit our `Cargo.lock` file.

Steps to reproduce:

```console
$ git checkout v0.6.0
$ cargo check
    Checking hotg-rune-core v0.6.1-dev (/home/michael/Documents/hotg-ai/rune/crates/rune-core)
    Checking hotg-rune-syntax v0.6.1-dev (/home/michael/Documents/hotg-ai/rune/crates/syntax)
    Checking hotg-rune-codegen v0.6.1-dev (/home/michael/Documents/hotg-ai/rune/crates/codegen)
    Finished dev [unoptimized + debuginfo] target(s) in 4.51s
$ cargo update -p cargo_toml
    Updating crates.io index
    Updating cargo_toml v0.9.2 -> v0.9.3
    Updating serde v1.0.127 -> v1.0.130
    Updating serde_derive v1.0.127 -> v1.0.130
$ cargo check
   ...
    Checking hotg-rune-codegen v0.6.1-dev (/home/michael/Documents/hotg-ai/rune/crates/codegen)
error[E0277]: the trait bound `toml::Value: Default` is not satisfied
   --> crates/codegen/src/manifest.rs:29:25
    |
29  |           workspace: Some(Workspace {
    |  _________________________^
30  | |             members: vec![String::from(".")],
31  | |             default_members: vec![String::from(".")],
32  | |             ..Default::default()
33  | |         }),
    | |_________^ the trait `Default` is not implemented for `toml::Value`
    |
    = note: required because of the requirements on the impl of `Default` for `Workspace`
note: required by `std::default::Default::default`
   --> /home/michael/.rustup/toolchains/nightly-2021-08-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/default.rs:116:5
    |
116 |     fn default() -> Self;
    |     ^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0277`.
error: could not compile `hotg-rune-codegen` due to previous error
```

**Comment by Michael-F-Bryan** [comment]
I've created a ticket for this upstream: https://gitlab.com/crates.rs/cargo_toml/-/issues/8.

**Comment by Michael-F-Bryan** [comment]
This was resolved upstream by yanking the version of `cargo_toml` which introduced the backwards incompatible-change. You can install with `cargo` again :partying_face:
