### ISSUE TITLE
Build fails when installing cli

### ISSUE THREAD

**Issue by amar-1977** [hotg-ai/rune#293]
Following the [tutorial](https://hotg.dev/docs/).

When I run the  [install command](https://hotg.dev/docs/#install-from-source), the complier fails and I see the following error:

`failed to run custom build command for wasm3-sys v0.1.2`

Here is the complete error message:

> error: failed to run custom build command for `wasm3-sys v0.1.2`
> 
> Caused by:
> 
> process didn't exit successfully: `/var/folders/8g/xctt18ln2fvdlvxgkp12f8bh0000gn/T/cargo-installgpuYB6/release/build/wasm3-sys-aaa72087975d306e/build-script-build` (exit status: 101)
>   --- stderr
>   thread 'main' panicked at 'Unable to generate bindings: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /.cargo/registry/src/github.com-1ecc6299db9ec823/wasm3-sys-0.1.2/build.rs:78:35
>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> warning: build failed, waiting for other jobs to finish...
> error: failed to compile `hotg-rune-cli v0.7.1-dev (https://github.com/hotg-ai/rune#999c54f4)`, intermediate artifacts can be found at `/var/folders/8g/xctt18ln2fvdlvxgkp12f8bh0000gn/T/cargo-installgpuYB6`

Caused by:
  build failed

**Comment by Michael-F-Bryan** [comment]
We recently added WASM3 as a way to execute WebAssembly and that brought along a requirement that `bindgen` is installed when building the CLI program (`cargo install bindgen`).

You aren't the first person to run into this (see #283) so I've made a PR to update the install docs.

**Comment by Michael-F-Bryan** [comment]
I think it's safe to mark this as resolved. @amar-1977 feel free to re-open the ticket if there is anything else that needs addressing.
