### ISSUE TITLE
Need a proc-block for tokenization

### ISSUE THREAD

**Issue by Mohit0928** [hotg-ai/rune#296]
For NLP related tasks, we will need a proc block that will take Sentences as input and will return outputs

    1. output ids (tokenizer converts tokens using vocab file)
    2. output masks (1 for useful tokens, 0 for padding)
    3. output segments (for 2 text training: 0 for the first one, 1 for the second one)
    
These outputs will serve as input to [Albert](https://tfhub.dev/tensorflow/albert_lite_base/1), [Text Classification,](https://www.tensorflow.org/lite/examples/text_classification/overview) etc.

**Approach**
We first take the sentence and tokenize it. A BERT sequence has the following format:

      - single sequence: [CLS] X [SEP]
      - pair of sequences: [CLS] A [SEP] B [SEP]
      E.g.  
      text = "Here is the sentence I want embeddings for."
      tokenized text = "[CLS] " + text + " [SEP]": ['[CLS]', 'here', 'is', 'the', 'sentence', 'i', 'want', 'em', '##bed', '##ding', '##s', 'for', '.', '[SEP]']

1. **Output Token ids**
BERT has a vocabulary of around 30k words. We will map the token strings to their vocabulary indices. Words that are not part of vocabulary are represented as subwords and characters. The output token ids will be a list of words indices. E.g. If the sentence is " After stealing money from the bank vault, the bank robber was seen fishing on the Mississippi river bank.":
```
[CLS]           101
after         2,044
stealing     11,065
money         2,769
from          2,013
the           1,996
bank          2,924
vault        11,632
,             1,010
the           1,996
bank          2,924
robber       27,307
was           2,001
seen          2,464
fishing       5,645
on            2,006
the           1,996
mississippi   5,900
river         2,314
bank          2,924
.             1,012
[SEP]           102
```
2. **Output Masks**
Mask values selected in [0, 1]:

    - 1 for useful tokens
    - 0 for padding

3. **Output segments**
BERT is trained on and expects sentence pairs, using 1s and 0s to distinguish between the two sentences. That is, for each token in “tokenized_text,” we must specify which sentence it belongs to: sentence 0 (a series of 0s) or sentence 1 (a series of 1s).

```
sentence_tokens: ['[CLS]', 'this', 'is', 'a', 'nice', 'sentence', '.', '[SEP]']
print(output_ids): [101, 2023, 2003, 1037, 3835, 6251, 1012, 102, 0, 0,......., 0]  # Size of this array will be max sequence length that model can take as input
print(output_masks): [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, .........., 0]
print(output_segments): [0, 0, 0, 0, 0, 0, 0, ..........., 0]      # As there is only one sentence so all elements of the array will be 0
```

Size of 3 arrays will be max sequence length that model can take as input

**Comment by Michael-F-Bryan** [comment]
@Mohit0928 do you know if an algorithm already exists for doing this sort of tokenizing in Rust?

**Comment by Mohit0928** [comment]
@Michael-F-Bryan, I will check and let you know.

**Comment by Mohit0928** [comment]
@Michael-F-Bryan, I checked, and there is [tokenizers ](https://crates.io/crates/tokenizers) crate. We can use this for our purpose. There are three main types of tokenizers used in **Transformers**: 

    1. Byte-Pair Encoding (BPE)
    2. WordPiece
    3. SentencePiece

This crate supports the first 2 tokenizers. As of now, these 2 will be enough to serve our purpose. The pipeline will look something like this:
1. We will take English sentences as input (right now, we don't support this in our "capability". I will add a ticket for this too.)
2. This English sentence will serve as input to the tokenizer proc-block, which will give us 3 outputs:
     a. output_ids
     b. output_masks
     c. output_segments
3. These will act as input to the NLP model (either all 3 or 2 or 1)

Please let me know when you get time. We can discuss how to proceed further and can help you out in building this.

**Comment by Michael-F-Bryan** [comment]
Looking through the `tokenizer` crate's `Cargo.toml` file I don't think it will be suitable. A Rune runs in a constrained environment with no access to things like the file system, threads, or the network, yet `tokenizers` pulls in crates like `rayon`, `clap`, and `reqwest` (why do they need a HTTP client?!).

Even if those dependencies could be compiled to WebAssembly, we'd still have the issue that a fresh build of a Rune which uses a proc block that depends on the `tokenizers` crate will take 4 or 5 minutes.

My suggestion would be that you find the basic syntax/definition for just the tokenizing algorithms we care about and implement your own `no_std` parser in Rust (preferably without using `regex` because that's quite a chunky dependency). That way the tokenizing proc block does *just* what it needs to without slowing down the build process by pulling in extra dependencies.

**Comment by Michael-F-Bryan** [comment]
This is already implemented as the `tokenizer` proc-block in the proc-blocks repo.
