### ISSUE TITLE
Need to support UTF8 data type as input from outside in the rune

### ISSUE THREAD

**Issue by Mohit0928** [hotg-ai/rune#298]
In our "capability", we don't support English sentences (UTF8) as input. We are going to need this capability to support NLP models in the rune. (mentioned in #296)

**Comment by Michael-F-Bryan** [comment]
You should be able to use the RAW capability (e.g. `--raw my-input.txt`) for this. From what I understand, most ML frameworks treat "strings" as just long `u8` tensors padded with zeroes to the right length (@SamLeroux or @meelislootus feel free to correct me here).

**Comment by Michael-F-Bryan** [comment]
I'm closing this ticket as it is resolved by using `u8` tensors and converting them to UTF-8 strings with `core::str::from_utf8()`.
