### ISSUE TITLE
Link for "API Docs" in README.md broken 

### ISSUE THREAD

**Issue by owen-duncan-snobel** [hotg-ai/rune#304]
The link for the API Docs in the [README.md ](https://github.com/hotg-ai/rune#rune)is broken. It redirects to https://hotg-ai.github.io/rune/rune_runtime/index.html

Not sure if it is supposed to link to https://hotg.dev/docs/ or a separate site for ghpages,etc.

**Comment by Michael-F-Bryan** [comment]
Thanks for picking up on this @owen-duncan-snobel!

The API docs are actually for the Rust crates which make up the Rune project, so the CLI program, the compiler, and so on. That way if you are wanting to embed the Rune runtime in your Rust apps you can see what is available.
