### ISSUE TITLE
rune inspect crashes on WSL

### ISSUE THREAD

**Issue by f0rodo** [hotg-ai/rune#307]
Details here: https://discord.com/channels/843552361212805180/872328451728748544/888625888806187118

```thread 'main' panicked at 'The project uses version control', /home/stephx/.cargo/registry/src/github.com-1ecc6299db9ec823/hotg-rune-cli-0.7.0/src/inspect.rs:56:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

**Comment by Michael-F-Bryan** [comment]
This is the actual error message

```
thread 'main' panicked at 'The project uses version control', /home/stephx/.cargo/registry/src/github.com-1ecc6299db9ec823/hotg-rune-cli-0.7.0/src/inspect.rs:56:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It [looks like](https://github.com/hotg-ai/rune/blob/be4b296329efa62355b58f67843de20d3794c2d8/crates/rune-cli/src/inspect.rs#L53-L58) we assume `hotg-rune-cli` was installed with a `git` repository, but crates.io doesn't keep the `.git` folder around.
