### ISSUE TITLE
ops error in the NLP-BERT model even while using the Rune librunecoral version

### ISSUE THREAD

**Issue by Mohit0928** [hotg-ai/rune#323]
I tried to test the NLP mobilebert_qa.tflite model with the new `Rune librunecoral version`, but I'm still getting the same old ops error. Here is all the [codebase](https://github.com/hotg-ai/test-runes/tree/master/nlp/bert) for mobilebert _qa.tflite, which contains proc-blocks, model, rune, etc.

```
INFO  hotg_rune_cli::run::command] Running rune: bert.rune
ERROR: Didn't find op for builtin opcode 'FULLY_CONNECTED' version '9'

ERROR: Registration failed.

Error: Unable to initialize the virtual machine

Caused by:
    0: Unable to call the _manifest function
    1: RuntimeError: Unable to load the model
           at <unnamed> (<module>[58]:0x45f5)
           at <unnamed> (<module>[56]:0x3fa6)
    2: Unable to load the model
    3: Unable to initialize the model interpreter
    4: `failed to build`
```

**Comment by Michael-F-Bryan** [comment]
[Looking at the `librunecoral` repo](https://github.com/hotg-ai/librunecoral/blob/fba3916783243612c2ad3978ccdf95bdbefc8888/WORKSPACE#L12), it seems like we're currently pinned to tensorflow/tensorflow@919f693420e35d00c8d0a42100837ae3718f7927 (August 10th, 2021), which I assume would have the `FULLY_CONNECTED` opcode.

It may also be that someone has taken a normal TensorFlow model and converted it to TensorFlow Lite without checking that the TensorFlow Lite interpreter has an implementation for `FULLY_CONNECTED` or the conversion was made using a different version of TensorFlow Lite.

**Comment by Mohit0928** [comment]
@Michael-F-Bryan, should I close this now? As the error was due to the improper installation of [librunecoral repo](https://github.com/hotg-ai/librunecoral/blob/fba3916783243612c2ad3978ccdf95bdbefc8888/WORKSPACE#L12).

**Comment by Michael-F-Bryan** [comment]
It sounds like this has been fixed by switching to a newer version of TensorFlow Lite (`librunecoral`).
