### ISSUE TITLE
Model Input for Person Detection needs fix

### ISSUE THREAD

**Issue by Mi1ind** [hotg-ai/rune#84]
the [`to_rgb8`](https://github.com/hotg-ai/rune/blob/cdd6ac9cc3aed328d4678f0c071264f99a4ba875/rune/src/run.rs#L115)  function converts pixels to a value between 0 and 255.

each pixel converted to its rgb value should have 3 numbers so the size that the model should read is `96 x 96 x 3` (with the image being `96 x 96` pixels large), but the length of the model being read is `96 x 96`.

This is what the first 2 pixels are supposed to be

> (x, y) position - RGB Value
> 1, 1 - 212, 212, 212
> 2, 1 - 213, 213, 213

This is part of the first line of the data sent to the Model:
```
[2021-03-18T23:32:09.529Z DEBUG rune_runtime::runtime] Model 1 input: [212, 212, 212, 213, 213, 213,
```

Expected and actual data values are the same, so the model is only reading 1/3 of the photo which is why it keeps outputting no person.

**Comment by Michael-F-Bryan** [comment]
This was fixed by #149 when we wired up the pixel format argument to our image capability.
